// Generated by scripts/tiktok/make_tiktok.py — do not edit by hand.
export const TIKTOK_PACK = [
  {
    "id": "t01",
    "image": "https://www.libralparty.net/assets/tiktok/t01.jpg",
    "caption": "הלילה הבא שלכם מתחיל כאן 🌙 מסיבות, מוזיקה וקהילה מכבדת בישראל. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t02",
    "image": "https://www.libralparty.net/assets/tiktok/t02.jpg",
    "caption": "קהילה מכבדת, חיבורים מעניינים 🩶 מרחב של חופש וכבוד הדדי. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t03",
    "image": "https://www.libralparty.net/assets/tiktok/t03.jpg",
    "caption": "פחות שגרה, יותר לילה ✨ המסיבה הבאה שלכם כבר מחכה. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t04",
    "image": "https://www.libralparty.net/assets/tiktok/t04.jpg",
    "caption": "חדש באתר 📲 התראות ישירות לנייד על מסיבות חדשות. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t05",
    "image": "https://www.libralparty.net/assets/tiktok/t05.jpg",
    "caption": "כל המסיבות בלוח אחד 📅 בוחרים לילה ונרשמים בדקה. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t06",
    "image": "https://www.libralparty.net/assets/tiktok/t06.jpg",
    "caption": "מפיקי אירועים 📣 מפרסמים את האירוע באתר הקהילה. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t07",
    "image": "https://www.libralparty.net/assets/tiktok/t07.jpg",
    "caption": "מנוי באתר = הכל במקום אחד 💎 אזור אישי, מועדפים והתראות. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  },
  {
    "id": "t08",
    "image": "https://www.libralparty.net/assets/tiktok/t08.jpg",
    "caption": "חבל להישאר בחוץ 🌟 מצטרפים לקהילה. הקישור בביו. 18+ #מסיבות #חיי_לילה #קהילה #ישראל #18plus #LIBRALPARTY"
  }
];
