/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdvertiserIndexRouteImport } from './routes/advertiser/index'
import { Route as ForumVerifyEmailRouteImport } from './routes/forum/verify-email'
import { Route as ForumResetPasswordRouteImport } from './routes/forum/reset-password'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'
import { Route as AdvertiserRegisterRouteImport } from './routes/advertiser/register'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserIndexRoute = AdvertiserIndexRouteImport.update({
  id: '/advertiser/',
  path: '/advertiser/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumVerifyEmailRoute = ForumVerifyEmailRouteImport.update({
  id: '/forum/verify-email',
  path: '/forum/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumResetPasswordRoute = ForumResetPasswordRouteImport.update({
  id: '/forum/reset-password',
  path: '/forum/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserRegisterRoute = AdvertiserRegisterRouteImport.update({
  id: '/advertiser/register',
  path: '/advertiser/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/advertiser/register': typeof AdvertiserRegisterRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/forum/reset-password': typeof ForumResetPasswordRoute
  '/forum/verify-email': typeof ForumVerifyEmailRoute
  '/advertiser/': typeof AdvertiserIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/advertiser/register': typeof AdvertiserRegisterRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/forum/reset-password': typeof ForumResetPasswordRoute
  '/forum/verify-email': typeof ForumVerifyEmailRoute
  '/advertiser': typeof AdvertiserIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/advertiser/register': typeof AdvertiserRegisterRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/forum/reset-password': typeof ForumResetPasswordRoute
  '/forum/verify-email': typeof ForumVerifyEmailRoute
  '/advertiser/': typeof AdvertiserIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/shop'
    | '/sitemap.xml'
    | '/tickets'
    | '/advertiser/register'
    | '/blog/$postId'
    | '/forum/reset-password'
    | '/forum/verify-email'
    | '/advertiser/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/shop'
    | '/sitemap.xml'
    | '/tickets'
    | '/advertiser/register'
    | '/blog/$postId'
    | '/forum/reset-password'
    | '/forum/verify-email'
    | '/advertiser'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/contact'
    | '/login'
    | '/register'
    | '/shop'
    | '/sitemap.xml'
    | '/tickets'
    | '/advertiser/register'
    | '/blog/$postId'
    | '/forum/reset-password'
    | '/forum/verify-email'
    | '/advertiser/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TicketsRoute: typeof TicketsRoute
  AdvertiserRegisterRoute: typeof AdvertiserRegisterRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  ForumResetPasswordRoute: typeof ForumResetPasswordRoute
  ForumVerifyEmailRoute: typeof ForumVerifyEmailRoute
  AdvertiserIndexRoute: typeof AdvertiserIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/': {
      id: '/advertiser/'
      path: '/advertiser'
      fullPath: '/advertiser/'
      preLoaderRoute: typeof AdvertiserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/verify-email': {
      id: '/forum/verify-email'
      path: '/forum/verify-email'
      fullPath: '/forum/verify-email'
      preLoaderRoute: typeof ForumVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/reset-password': {
      id: '/forum/reset-password'
      path: '/forum/reset-password'
      fullPath: '/forum/reset-password'
      preLoaderRoute: typeof ForumResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/register': {
      id: '/advertiser/register'
      path: '/advertiser/register'
      fullPath: '/advertiser/register'
      preLoaderRoute: typeof AdvertiserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TicketsRoute: TicketsRoute,
  AdvertiserRegisterRoute: AdvertiserRegisterRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  ForumResetPasswordRoute: ForumResetPasswordRoute,
  ForumVerifyEmailRoute: ForumVerifyEmailRoute,
  AdvertiserIndexRoute: AdvertiserIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
